### ISSUE TITLE
Qt license 

### ISSUE THREAD

**Issue by Anywhere-Music-Player** [erayzesen/Turquoise2D#2]
Overall, this design of idea of how it should be done.. like how to create a cross-platform engine with C++ and have an editor with a proper framework, like Qt. That’s idea was in my mind for many years..
However, this is not allow you to publish games, right?

**Comment by erayzesen** [comment]
Hi. The game framework is Independent from the editor. The editor writed in the Qt environment and licenced as opensource. So, we haven't problem with the qt licence when release a game if you want to ask that question. Qt licence allows open source applications.

**Comment by Anywhere-Music-Player** [comment]
So, the editor should be just open-source and I can use it for developing my game, publish on the Apple Store and I don’t have to pay for any Qt license?

**Comment by erayzesen** [comment]
Of course.

**Comment by raydelto** [comment]
> So, the editor should be just open-source and I can use it for developing my game, publish on the Apple Store and I don’t have to pay for any Qt license?

That's correct.  This repo is using the open source version of Qt. It would allow you to build your games without any issues. Please take in consideration that Turquoise2D is a work in progress. That's why its creator @erayzesen made it open source this week, so that we (the open source community) polish it, and make its first release :)

**Comment by raydelto** [comment]
This thread started as an **issue**. There is no actual issue to report here. So @erayzesen you can close this issue now :) .

**Comment by Anywhere-Music-Player** [comment]
I was just banned on the cocos2d-x forum, because of editor I supported and pushed to the masses: https://github.com/KAMIKAZEUA/SpriteBuilderX
https://discuss.cocos2d-x.org/t/spritebuilderx-editor-for-cocos2d-x-with-c-support/34916

Short story: they abandoned C++ support and moved to Javascript editor-engine which is tend to be just a clone of Unity, I m talking about cocos creator. Any my criticism in favor of this choice(JS) was supported on the forum by other C++ developers, but it was also carefully checked and suppressed by the moderators there. Some of my comments was rude, yea, but I just have a feelings for the cocos2d-x and it was painful for me to see how they killing it... 

But what is more funny, I also told them that the most appropriate choice is an editor such as yours: made in C++ and uses Qt. But they completely ignored this, so don’t hope that anyone on the forum needs your editor (I’m talking about official representatives).

So I can ask only here.

———
Also, what you should know - from what I see and understand from all my experience with the engine: cocos2d-x is abandoned and dead.

No one uses or supports it. Over the past half year or even more, not a single adequate improvement has been made that is aimed at developing new functions and thinking over the future of this engine.

Check this https://github.com/cocos2d/cocos2d-x/issues/20502

Also, this is not the end. They ban me on the github too:

> You are blocked from the cocos2d organization and cannot comment because of this content.
https://github.com/cocos2d/cocos2d-x/issues/20396

Can you imagine! I just was banned because I asked - how new v4 was tested, because I know it has a lot of problems and should be tested and fixed on many devices. It was just like made in a hurry and anyhow, just to be released.. 

Another example I created a simple UI bug and it’s still not fixed for years: https://github.com/cocos2d/cocos2d-x/issues/18616

@erayzesen :) sorry for too much text and I will never post any issues here any more. Just wanted to say it all.

**Comment by raydelto** [comment]
Thanks @KAMIKAZEUA for reaching out.  What's the state of your editor? do you need help from the development community?  is there anyway we could merge efforts between Turquoise2D and SpriteBuilderX to create a game editor for those who prefer to code in C++?

**Comment by Anywhere-Music-Player** [comment]
I'm using Unity, this is only way quickly and stably develop games for mobile.
I'm not sure about what community you talking about, I don't know anyone. It's all abandoned. 
No future for any kind of editor with C++, this is years task and requires a huge investment.

**Comment by erayzesen** [comment]
Thanks for some informations @KAMIKAZEUA. I know SpriteBuilderX project and it's a good tool. Maybe you want to look Turquoise2D project to help in the future : )

**Comment by Anywhere-Music-Player** [comment]
Cocos2d-x is dead and abandoned, there’s no any sense to spend time on it.

The only way is to create a new engine from scratch. I have such idea in my mind, but it’s again requires a years of work of a team minimum 5 developers and a clear and right vision direction of the engine..
And Unity is free, so it’s would be nearly impossible to gain some popularity with any new product. This is too risky and costly.
However, I’d defend tryout this! Just where to get money for the 2+ years of work?..
